import type { Character, ShopItem } from '@/types';

export const initialCharacter: Character = {
  name: 'Hero',
  level: 1,
  xp: 0,
  xpToNextLevel: 100,
  coins: 50,
  mood: 3,
  equipment: {
    hat: null,
    accessory: null,
    outfit: null,
  },
  ownedItems: [],
};

export const shopItems: ShopItem[] = [
  {
    id: 'hat_witch',
    name: 'Witch Hat',
    emoji: '🧙',
    description: 'A pointy magical hat',
    price: 50,
    type: 'hat',
    color: '#ff6b6b',
  },
  {
    id: 'hat_crown',
    name: 'Royal Crown',
    emoji: '👑',
    description: 'For the royalty in you',
    price: 120,
    type: 'hat',
    color: '#ffb3d9',
  },
  {
    id: 'hat_wizard',
    name: 'Wizard Hat',
    emoji: '🎩',
    description: 'Classic wizard vibes',
    price: 80,
    type: 'hat',
    color: '#ffd700',
  },
  {
    id: 'hat_santa',
    name: 'Santa Hat',
    emoji: '🎅',
    description: 'Ho ho ho!',
    price: 60,
    type: 'hat',
    color: '#a8d8ea',
  },
  {
    id: 'accessory_glasses',
    name: 'Cool Glasses',
    emoji: '😎',
    description: 'Stay cool',
    price: 40,
    type: 'accessory',
    color: '#d4a574',
  },
  {
    id: 'accessory_monocle',
    name: 'Monocle',
    emoji: '🧐',
    description: 'Very distinguished',
    price: 70,
    type: 'accessory',
    color: '#8b7355',
  },
  {
    id: 'accessory_bow',
    name: 'Magic Bow',
    emoji: '🎀',
    description: 'A pretty magical bow',
    price: 45,
    type: 'accessory',
    color: '#9b59b6',
  },
  {
    id: 'accessory_star',
    name: 'Star Badge',
    emoji: '⭐',
    description: 'You are a star!',
    price: 35,
    type: 'accessory',
    color: '#7dbb8a',
  },
  {
    id: 'outfit_knight',
    name: 'Knight Armor',
    emoji: '⚔️',
    description: 'For brave questing',
    price: 150,
    type: 'outfit',
    color: '#795548',
  },
  {
    id: 'outfit_wizard_robe',
    name: 'Wizard Robe',
    emoji: '🧙‍♂️',
    description: 'Channel the arcane',
    price: 130,
    type: 'outfit',
    color: '#e74c3c',
  },
  {
    id: 'outfit_fairy',
    name: 'Fairy Dress',
    emoji: '🧚',
    description: 'Light as a feather',
    price: 110,
    type: 'outfit',
    color: '#9b59b6',
  },
  {
    id: 'outfit_ninja',
    name: 'Ninja Suit',
    emoji: '🥷',
    description: 'Stealthy and swift',
    price: 140,
    type: 'outfit',
    color: '#f39c12',
  },
  {
    id: 'hat_party',
    name: 'Party Hat',
    emoji: '🎉',
    description: 'Every day is a party',
    price: 30,
    type: 'hat',
    color: '#2d6a4f',
  },
  {
    id: 'hat_tophat',
    name: 'Top Hat',
    emoji: '🎩',
    description: 'Very fancy indeed',
    price: 90,
    type: 'hat',
    color: '#f4a261',
  },
  {
    id: 'hat_cap',
    name: 'Baseball Cap',
    emoji: '🧢',
    description: 'Casual and cool',
    price: 25,
    type: 'hat',
    color: '#1a1a2e',
  },
  {
    id: 'accessory_wand',
    name: 'Magic Wand',
    emoji: '🪄',
    description: 'Cast spells of productivity',
    price: 85,
    type: 'accessory',
    color: '#a8c5a0',
  },
  {
    id: 'outfit_explorer',
    name: 'Explorer Outfit',
    emoji: '🗺️',
    description: 'Ready for adventure',
    price: 120,
    type: 'outfit',
    color: '#d4a574',
  },
  {
    id: 'outfit_mage',
    name: 'Mage Robes',
    emoji: '🔮',
    description: 'Mystical and powerful',
    price: 160,
    type: 'outfit',
    color: '#f5c6d0',
  },
  {
    id: 'accessory_shield',
    name: 'Mini Shield',
    emoji: '🛡️',
    description: 'Protect yourself from procrastination',
    price: 65,
    type: 'accessory',
    color: '#6bcb77',
  },
  {
    id: 'hat_flower',
    name: 'Flower Crown',
    emoji: '🌸',
    description: 'Bloom where you are planted',
    price: 55,
    type: 'hat',
    color: '#8b7355',
  },
];
