import type { GameState, ShopItem } from '@/types';

const DEFAULT_SHOP_ITEMS: ShopItem[] = [
  {
    id: 'hat-1',
    name: 'Witch Hat',
    emoji: '🧙',
    description: 'A mystical pointed hat',
    cost: 50,
    category: 'hat',
    owned: false,
    equipped: false,
  },
  {
    id: 'hat-2',
    name: 'Crown',
    emoji: '👑',
    description: 'For the royalty in you',
    cost: 120,
    category: 'hat',
    owned: false,
    equipped: false,
  },
  {
    id: 'hat-3',
    name: 'Party Hat',
    emoji: '🎉',
    description: 'Always ready to celebrate',
    cost: 30,
    category: 'hat',
    owned: false,
    equipped: false,
  },
  {
    id: 'acc-1',
    name: 'Magic Wand',
    emoji: '🪄',
    description: 'Cast spells of productivity',
    cost: 80,
    category: 'accessory',
    owned: false,
    equipped: false,
  },
  {
    id: 'acc-2',
    name: 'Rainbow Scarf',
    emoji: '🌈',
    description: 'Colorful and cozy',
    cost: 60,
    category: 'accessory',
    owned: false,
    equipped: false,
  },
  {
    id: 'outfit-1',
    name: 'Wizard Robe',
    emoji: '🧥',
    description: 'Ancient robes of wisdom',
    cost: 100,
    category: 'outfit',
    owned: false,
    equipped: false,
  },
  {
    id: 'outfit-2',
    name: 'Knight Armor',
    emoji: '🛡️',
    description: 'Brave and bold',
    cost: 150,
    category: 'outfit',
    owned: false,
    equipped: false,
  },
];

export function getInitialState(): GameState {
  return {
    character: {
      name: 'Hero',
      level: 1,
      xp: 0,
      xpToNextLevel: 100,
      coins: 50,
      mood: 'neutral',
      equipment: {
        hat: null,
        accessory: null,
        outfit: null,
      },
    },
    tasks: [],
    projects: [],
    shopItems: DEFAULT_SHOP_ITEMS,
    streak: 0,
    lastActiveDate: null,
    notifications: [],
  };
}
