import type { GameState, ShopItem } from '@/types';

export const INITIAL_STATE: GameState = {
  character: {
    name: 'Adventurer',
    level: 1,
    xp: 0,
    xpToNextLevel: 100,
    coins: 50,
    equipment: {
      hat: null,
      outfit: null,
      accessory: null,
      background: null,
      pet: null,
    },
    mood: 'happy',
  },
  tasks: [],
  projects: [],
  shopItems: [],
  totalTasksCompleted: 0,
  streak: 0,
  lastCompletedDate: null,
};

export const SHOP_ITEMS: ShopItem[] = [
  // Hats
  {
    id: 'hat_mushroom',
    name: 'Mushroom Cap',
    description: 'A cute red mushroom hat!',
    category: 'hat',
    price: 30,
    emoji: '🍄',
    color: '#ff6b6b',
    owned: false,
    equipped: false,
  },
  {
    id: 'hat_flower',
    name: 'Flower Crown',
    description: 'A lovely floral crown.',
    category: 'hat',
    price: 40,
    emoji: '🌸',
    color: '#ffb3d9',
    owned: false,
    equipped: false,
  },
  {
    id: 'hat_star',
    name: 'Star Hat',
    description: 'Shine bright like a star!',
    category: 'hat',
    price: 60,
    emoji: '⭐',
    color: '#ffd700',
    owned: false,
    equipped: false,
  },
  {
    id: 'hat_rainbow',
    name: 'Rainbow Beanie',
    description: 'All colors of the rainbow!',
    category: 'hat',
    price: 80,
    emoji: '🌈',
    color: '#a8d8ea',
    owned: false,
    equipped: false,
  },
  // Outfits
  {
    id: 'outfit_cozy',
    name: 'Cozy Sweater',
    description: 'Warm and comforting.',
    category: 'outfit',
    price: 50,
    emoji: '🧶',
    color: '#d4a574',
    owned: false,
    equipped: false,
  },
  {
    id: 'outfit_adventurer',
    name: 'Adventurer Cloak',
    description: 'Ready for any quest!',
    category: 'outfit',
    price: 70,
    emoji: '🧥',
    color: '#8b7355',
    owned: false,
    equipped: false,
  },
  {
    id: 'outfit_magical',
    name: 'Magical Robe',
    description: 'Imbued with mystical power.',
    category: 'outfit',
    price: 100,
    emoji: '✨',
    color: '#9b59b6',
    owned: false,
    equipped: false,
  },
  {
    id: 'outfit_garden',
    name: 'Garden Dress',
    description: 'Fresh as a spring garden.',
    category: 'outfit',
    price: 65,
    emoji: '🌿',
    color: '#7dbb8a',
    owned: false,
    equipped: false,
  },
  // Accessories
  {
    id: 'acc_glasses',
    name: 'Round Glasses',
    description: 'Bookish and adorable.',
    category: 'accessory',
    price: 25,
    emoji: '👓',
    color: '#795548',
    owned: false,
    equipped: false,
  },
  {
    id: 'acc_scarf',
    name: 'Cozy Scarf',
    description: 'Keeps you warm on quests.',
    category: 'accessory',
    price: 35,
    emoji: '🧣',
    color: '#e74c3c',
    owned: false,
    equipped: false,
  },
  {
    id: 'acc_wand',
    name: 'Magic Wand',
    description: 'For casting productivity spells.',
    category: 'accessory',
    price: 55,
    emoji: '🪄',
    color: '#9b59b6',
    owned: false,
    equipped: false,
  },
  {
    id: 'acc_lantern',
    name: 'Lantern',
    description: 'Lights your path forward.',
    category: 'accessory',
    price: 45,
    emoji: '🏮',
    color: '#f39c12',
    owned: false,
    equipped: false,
  },
  // Backgrounds
  {
    id: 'bg_forest',
    name: 'Enchanted Forest',
    description: 'A magical woodland scene.',
    category: 'background',
    price: 80,
    emoji: '🌲',
    color: '#2d6a4f',
    owned: false,
    equipped: false,
  },
  {
    id: 'bg_beach',
    name: 'Sunny Beach',
    description: 'Waves and warm sand.',
    category: 'background',
    price: 80,
    emoji: '🏖️',
    color: '#f4a261',
    owned: false,
    equipped: false,
  },
  {
    id: 'bg_space',
    name: 'Starry Night',
    description: 'Adventure among the stars.',
    category: 'background',
    price: 120,
    emoji: '🌙',
    color: '#1a1a2e',
    owned: false,
    equipped: false,
  },
  {
    id: 'bg_cottage',
    name: 'Cozy Cottage',
    description: 'Home sweet home.',
    category: 'background',
    price: 90,
    emoji: '🏡',
    color: '#a8c5a0',
    owned: false,
    equipped: false,
  },
  // Pets
  {
    id: 'pet_cat',
    name: 'Tabby Cat',
    description: 'A fluffy companion!',
    category: 'pet',
    price: 60,
    emoji: '🐱',
    color: '#d4a574',
    owned: false,
    equipped: false,
  },
  {
    id: 'pet_bunny',
    name: 'Fluffy Bunny',
    description: 'Hops along with you.',
    category: 'pet',
    price: 60,
    emoji: '🐰',
    color: '#f5c6d0',
    owned: false,
    equipped: false,
  },
  {
    id: 'pet_dragon',
    name: 'Tiny Dragon',
    description: 'A fierce little friend.',
    category: 'pet',
    price: 150,
    emoji: '🐲',
    color: '#6bcb77',
    owned: false,
    equipped: false,
  },
  {
    id: 'pet_owl',
    name: 'Wise Owl',
    description: 'Knowledge is power!',
    category: 'pet',
    price: 90,
    emoji: '🦉',
    color: '#8b7355',
    owned: false,
    equipped: false,
  },
];
